name: "visual_dbn3"
model_type: DBN
hyperparams {
  base_epsilon: 0.01
  epsilon_decay: NONE
  epsilon_decay_half_life: 5000
  initial_momentum: 0.5
  final_momentum: 0.9
  momentum_change_steps: 3000
  sparsity: true
  sparsity_target: 0.05
  sparsity_cost: 0.01
  sparsity_damping: 0.9
  dropout: false
  dropout_prob: 0.5
  apply_weight_norm: false
  weight_norm: 3.0
  apply_l2_decay: true
  l2_decay: 0.001
  activation: LOGISTIC
  mf_steps: 1
  gibbs_steps: 1
}
layer {
  name: "visual_input_layer"
  dimensions: 1770
  param {
    name: "bias"
    initialization: CONSTANT
  }
  param {
    name: "bias_generative"
    initialization: PRETRAINED
    pretrained_model: "/home/chao/Lipreading_DBN/DBN_Models/visual_rbm1_LAST"
    pretrained_model_param_name: "bias"
  }
  is_input: true
  data_field {
    train: "visual_unlabelled"
    validation: "visual_labelled"
  }
}
layer {
  name: "visual_hidden1"
  dimensions: 2048
  param {
    name: "bias_generative"
    initialization: PRETRAINED
    pretrained_model: "/home/chao/Lipreading_DBN/DBN_Model/visual_dbn2_rbm_LAST"
  }
  param {
    name: "bias"
    initialization: PRETRAINED
    pretrained_model: "/home/chao/Lipreading_DBN/DBN_Model/visual_rbm1_LAST"
  }
}
layer {
  name: "visual_hidden2"
  dimensions: 1024
  param {
    name: "bias_generative"
    initialization: CONSTANT
  }
  param {
    name: "bias"
    initialization: PRETRAINED
    pretrained_model: "/home/chao/Lipreading_DBN/DBN_Model/visual_dbn2_rbm_LAST"
  }
  loss_function: SQUARED_LOSS
  performance_stats {
    compute_error: true
  }
}
layer {
  name: "visual_hidden3"
  dimensions: 256
  param {
    name: "bias"
    initialization: CONSTANT
  }
  performance_stats {
    compute_sparsity: true
  }
}
edge {
  node1: "visual_hidden1"
  node2: "visual_input_layer"
  param {
    name: "weight"
    initialization: PRETRAINED
    pretrained_model: "/home/chao/Lipreading_DBN/DBN_Model/visual_rbm1_LAST"
    transpose_pretrained: true
  }
}
edge {
  node1: "visual_hidden2"
  node2: "visual_hidden1"
  param {
    name: "weight"
    initialization: PRETRAINED
    pretrained_model: "/home/chao/Lipreading_DBN/DBN_Model/visual_dbn2_rbm_LAST"
    transpose_pretrained: true
  }
}
edge {
  node1: "visual_hidden2"
  node2: "visual_hidden3"
  directed: false
  param {
    name: "weight"
    initialization: DENSE_GAUSSIAN_SQRT_FAN_IN
    sigma: 1.0
  }
}

